// Movies

// Fetch landing page now playing (movies)
export const FETCH_NOW_PLAYING_MOVIES_REQUEST = "FETCH_NOW_PLAYING_MOVIES_REQUEST";
export const FETCH_NOW_PLAYING_MOVIES_SUCCESS = "FETCH_NOW_PLAYING_MOVIES_SUCCESS";
export const FETCH_NOW_PLAYING_MOVIES_FAIL = "FETCH_NOW_PLAYING_MOVIES_FAIL";


// TV Series

// Fetch landing page TV series currently on the air ()
export const FETCH_TV_SERIES_ON_AIR_REQUEST = "FETCH_TV_SERIES_ON_AIR_REQUEST"
export const FETCH_TV_SERIES_ON_AIR_SUCCESS = "FETCH_TV_SERIES_ON_AIR_SUCCESS"
export const FETCH_TV_SERIES_ON_AIR_FAIL = "FETCH_TV_SERIES_ON_AIR_FAIL"

