// Movies

// Fetch landing page now playing (movies)
export const FETCH_NOW_PLAYING_MOVIES_REQUEST = "FETCH_NOW_PLAYING_MOVIES_REQUEST";
export const FETCH_NOW_PLAYING_MOVIES_SUCCESS = "FETCH_NOW_PLAYING_MOVIES_SUCCESS";
export const FETCH_NOW_PLAYING_MOVIES_FAIL = "FETCH_NOW_PLAYING_MOVIES_FAIL";

